### ISSUE TITLE
Error flashing

### ISSUE THREAD

**Issue by webdevbrian** [pkourany/RC522_RFID#1]
My error is below, not sure what's going on:

    RFID.cpp: In member function 'void RFID::halt()':
RFID.cpp:512:13: warning: variable 'status' set but not used [-Wunused-but-set-variable]
     uint8_t status;
             ^
RFID.cpp: In member function 'uint8_t RFID::softSPITranser(uint8_t)':
RFID.cpp:532:3: error: 'PIN_MAP' was not declared in this scope
   PIN_MAP[_mosiPin].gpio_peripheral->BSRR = PIN_MAP[_mosiPin].gpio_pin; // Data High
   ^

RFID.cpp:534:3: error: 'PIN_MAP' was not declared in this scope
   PIN_MAP[_mosiPin].gpio_peripheral->BRR = PIN_MAP[_mosiPin].gpio_pin; // Data Low
   ^

RFID.cpp:536:3: error: 'PIN_MAP' was not declared in this scope
   PIN_MAP[_clockPin].gpio_peripheral->BSRR = PIN_MAP[_clockPin].gpio_pin; // Clock High
   ^

make[1]: *** [../build/target/user/platform-6RFID.o] Error 1
make: *** [user] Error 2

**Comment by pkourany** [comment]
@webdevbrian, a lot of things are changing with Photon and I will be updating all my libraries starting this weekend.  One issue, as you discovered, is related to PIN_MAP. :)

**Comment by webdevbrian** [comment]
Figured it was because of the photon, and this was geared for the core. Was reading a few things (from you!) about this, also with reeling in MDMA in about it.

Can't wait!!! Thank you very much sir.

**Comment by webdevbrian** [comment]
I wish I could help out in some way!
